### ISSUE TITLE
Buggy hover extensions should not be able to break other hover providers

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph-extension-api#105]
The sourcegraph-string-references extension [breaks code intelligence in certain places](https://github.com/lguychard/sourcegraph-string-references/issues/6). This should not be possible.

If one hover provider fails, other hover providers should continue to work.

I don't know which component is responsible for this so I am filing on this repo. Feel free to move.

cc @chrismwendt @sqs @felixfbecker @ijsnow

**Comment by slimsag** [comment]
@nicksnyder I've updated the title here to reflect that this is in specific about hover providers. This is also true of other things in extensions, e.g. references providers like the issue https://github.com/sourcegraph/sourcegraph-extension-api/issues/82 talks about.

If you're aware of other specific cases of this, let's file separate issues for those since the fixes will likely be independent

**Comment by slimsag** [comment]
@beyang If you can, please provide steps to reproduce it, e.g. what extensions did you have enabled that caused it?
