### ISSUE TITLE
Code intelligence hovers pop up on my hover link decorations, yuck

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph-extension-api#67]
My extension provides a decoration with some `after: { contentText: "...", linkURL: "..." }` and on GitHub.com the code intelligence hovers pop up when I move my mouse over it, which makes clicking the link really yucky:

![image](https://user-images.githubusercontent.com/3173176/45585161-caaff580-b894-11e8-8b3f-10347f2aa438.png)

**Comment by sqs** [comment]
I am still experiencing this (when using a dev browser extension built from master, because the fix is not yet released).

Repro:

1. Run a dev build of the browser extension (so you get this attempted fix)
1. In the browser extension options page, enable Sourcegraph extensions (feature flag)
1. Enable the https://sourcegraph.com/extensions/sourcegraph/git-extras extension
1. Go to https://github.com/sourcegraph/sourcegraph/blob/master/gulpfile.ts
1. Click the **Blame** button in the GitHub file toolbar (you should see a bunch of after-line blame decorations)

Sometimes hovering the after-line decorations shows the hover that would be correct for the last character. Sometimes it just shows a brief loading spinner in the hover then the hover goes away (it shouldn't show up at all on top of the after-line decorations, not even loading).

![screenshot from 2018-10-28 18-47-26](https://user-images.githubusercontent.com/1976/47625368-eccaa380-dae1-11e8-90ad-ada37d4cc96f.png)

**Comment by sqs** [comment]
False alarm...I think something was being cached or...??? But it's working now.

**Comment by slimsag** [comment]
Odd. Let me know if you see it again, this should be fixed both here & in Sourcegraph.
