### ISSUE TITLE
New feature: Enable local testing of a Sourcegraph extension before publishing

### ISSUE THREAD

**Issue by mhewett** [sourcegraph/sourcegraph-extension-api#92]
It would be nice to be able to test an extension on a local Sourcegraph installation before publishing it to the world.  Can we have a way to install an extension in a local installation, including Docker-based installations?

**Comment by sqs** [comment]
Yes, we absolutely want to add this. I will move this issue over to https://github.com/sourcegraph/sourcegraph/issues/489 because that's where it'll be implemented. I have also tentatively prioritized it for next month.

Note that https://github.com/sourcegraph/sourcegraph/issues/480 will also help here, and we will do that even sooner.
